spring.application.name=consumer
server.port=8081

# AWS Configuration
aws.region=us-west-2
aws.account.id=211125351505

# Consumer Configuration
consumer.threads=80
consumer.polling.wait.seconds=1
consumer.batch.size=10

# Logging
logging.level.consumer=INFO
logging.level.software.amazon.awssdk=WARN
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
# Server broadcast endpoint
server.broadcast.url=http://localhost:8080/api/broadcast
