server.port=8080
spring.application.name=Assignment2_ChatServer

# AWS Configuration
aws.region=us-west-2
aws.account.id=211125351505

# Logging
logging.level.server=INFO
logging.level.software.amazon.awssdk=WARN